<?php

namespace Database\Seeders;


use App\Models\Pricepub;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class PubSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trigger = [
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '3',
                'hours'            => '4',
                'hours_schedule'   => '07:00 - 00:30',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000', // done keseluruhan
                'price_launch'     => '50000' // per personil
                //total uang makan
                // price radius standar 
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '3',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '4',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '5',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '6',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '7',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '8',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '9',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '10',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '11',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '12',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'TRIGGER',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '13',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
        ];

        $pass = [
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '2',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '3',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '4',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '5',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '6',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '7',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '8',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '9',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '10',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'

            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '11',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '12',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'PASS',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '13',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
        ];


        $deka = [
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)), // sequence code 
                'personil'         => '2',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
                // nama partner
                // komisi value partner 
                // komisi percent partner 
                // deka percent 
                // deka value
                // tnos percent 
                // tnos value
                // value user
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '3',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '4',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '5',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '6',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '7',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '8',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '9',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '10',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '11',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '12',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
            [
                'mitra'            => 'DEKA',
                'code'             =>  strtoupper(Str::random(8)),
                'personil'         => '13',
                'hours'            => '4',
                'hours_schedule'   => '08:00 - 17:00',
                'total_day'        => '1 hari',
                'tnos_percent'     => '20%',
                'mitra_percent'    => '80%',
                'tnos_value'       => '800000',
                'mitra_value'      => '2800000',
                'price'            => '3600000',
                'is_active'        => '1',
                'free_radius'      => '10',
                'price_meeting'    => '500000',
                'price_launch'     => '50000'
            ],
        ];



        Pricepub::insert($trigger);
        Pricepub::insert($pass);
        Pricepub::insert($deka);
    }
}
